twig:
    default_path: '%kernel.project_dir%/templates'

    paths:
        '%kernel.project_dir%/vendor/knplabs/knp-paginator-bundle/templates': KnpPaginator

    form_themes: [
        'bootstrap_5_horizontal_layout.html.twig',
        'default/theme.html.twig'
        ]

when@test:
    twig:
        strict_variables: true
